name: Bug report
description: Report a bug in CineTCG
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: input
    id: version
    attributes:
      label: CineTCG version
      description: If from main, include the commit SHA.
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11 / macOS 14 / Ubuntu 24.04"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12.x"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      description: Step-by-step instructions to reproduce.
      placeholder: |
        1. Launch the game
        2. Click Ranked
        3. Play card X
        4. Crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs (redact personal info) or attach screenshots.
      render: text
    validations:
      required: false
