name: Feature request
description: Propose a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement!
        If this touches the rules engine, please note determinism/replay and schema impacts.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve and for whom?
      placeholder: "As a player, I want..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change at a high level.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / impact
      description: What files/areas likely change? (engine, client scenes, data schemas, services)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
